# This is a basic workflow to help you get started with Actions

name: Testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workfloecho "$DIR/jetbrains-toolbox" >> $DIR/jetbrains-toolbox.shw_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run install
        run: sudo $GITHUB_WORKSPACE/jetbrains-toolbox.sh

      # Runs a set of commands using the runners shell
      - name: Validate that symlink has been created
        run:  "[ -f /usr/local/bin/jetbrains-toolbox ]"
